### ISSUE TITLE
Mapping from database use column names

### ISSUE THREAD

**Issue by vlkong** [IBMDecisionOptimization/OPL-jdbc-custom-data-source#6]
From Daniel Junglas:

I have this table in the database:
```stringcol | intcol | floatcol
"one"     | 1      | 0.1
"two"     | 2      | 0.2
"three"   | 3      | 0.3
"four"    | 4      | 0.4
```

Then I define this in the `.mod`:

```tuple T {
   float  floatfield;
   string stringfield;
   int    intfield;
}
{T} tupleset = ...;
```

and in the `.xml` I do:

    ```<query name="tupleset">SELECT floatcol, stringcol, intcol FROM data4set</query>
```

This raises an exception:

```Reading tupleset using "SELECT floatcol, stringcol, intcol FROM data4set"
java.sql.SQLException: no such column: 'floatfield'
    at org.sqlite.jdbc3.JDBC3ResultSet.findColumn(JDBC3ResultSet.java:49)
    at org.sqlite.jdbc3.JDBC3ResultSet.getDouble(JDBC3ResultSet.java:375)
    at com.ibm.opl.customdatasource.JdbcCustomDataSource.readTupleSet(JdbcCustomDataSource.java:158)
    at com.ibm.opl.customdatasource.JdbcCustomDataSource.customRead(JdbcCustomDataSource.java:93)
    at com.ibm.opl.customdatasource.JdbcCustomDataSource.customRead(JdbcCustomDataSource.java:81)
    at ilog.opl.IloCustomOplDataSource$MyDS.read(IloCustomOplDataSource.java:32)
    at ilog.opl.opl_lang_wrapJNI.SwigDirector_IloOplDataSourceWrapper_read(opl_lang_wrapJNI.java:1146)
```

It seems the query use the name of the tuple field in the query. That looks a bug to me. The query should just pick the n-th value from the query so that the field names in the `.mod` can be different from the column names in the database. Moreover, you may want to fill the same tuple in different sets from multiple queries/tables so that it may even be impossible to align the field and column names.

**Comment by vlkong** [comment]
Note that this can be taken care of using the proper query, like:
SELECT floatcol as floatfield, strincol as stringfield, intcol as intfield from data4set

Thinking about it, this looks safer than taking fields in order, and using SQL aliasing isn't a big hit in perfs
